### PR TITLE
Alps 381 gyroscope

### PR DESCRIPTION
**Pull request by aberthet-gpsw**
This PR introduces the GyroscopeController, which controls the camera using the gyroscope of the device it is running on (if the device has a gyroscope). By default, the gyroscope is working on any project. It is linked to gopro/forgejs-plugins#3, which is a toggle button for the GyroscopeController.

There was an attempt to add the behavior of the PointerController while using the Gyroscope, but not completely successful. Those changes are kept in this PR, but they are deactivated for now. There will be reused in another future branch.

This PR also fixes the ALPS-588 feature request of inverting each axis of the PointerController.

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by ferrante** [comment]
Is there a way this can be reviewed and merged soon? It would be great to be able to use gyroscope on Safari iOS in forgejs.

**Comment by aberthet-gpsw** [comment]
@ferrante it should be done today !

**Comment by ferrante** [comment]
Great news, thx!

**Comment by rroux-gpsw** [comment]
@ferrante The review and merge is complete! If you have any feedback / testing about this feature on iOS. Have a nice day :)

**Pull request merged**
