### PR TITLE
Three.js r86 version

### PR DESCRIPTION
**Pull request by bbaudel-gpsw**
Upgrade to r86 of Three.js.

Need tests on all samples, minification, build process, Three.js externs

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by bbaudel-gpsw** [comment]
First test : all current samples are working

**Comment by aberthet-gpsw** [comment]
All samples are working with Chrome 59.0.3071.115, Firefox 54.0.1 and Safari 10.1.1 on OS X 10.11. I'll try to find an available desktop to test Edge.

**Comment by aberthet-gpsw** [comment]
All good on Edge on Windows 10 too.

**Pull request merged**
