### PR TITLE
Flat View - runtime setter of repeat properties

### PR DESCRIPTION
**Pull request by ygilquin-gpsw**
Enable setting repeat X/Y properties at runtime

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by ygilquin-gpsw** [comment]
Changes can be tested with change_view sample by opening a console and setting viewer.view.current.repeatX and repeatY to true/false

**Comment by rroux-gpsw** [comment]
I'm on it

**Comment by aberthet-gpsw** [comment]
Not merging this mess, see #41 for new PR

**Pull request closed without merging**
