### PR TITLE
ALPS-2105 - Camera limits

### PR DESCRIPTION
**Pull request by aberthet-gpsw**
I removed the notions of `limits` introduced by the multi resolution. It was really confusing with the already present limits in the `camera` object (with yaw/pitch min/max), so now we have only the camera one. But as the camera ones were not correct, the functioning was moved to use the `limits` one.

I also added a simple sort based on the face available for multi resolution and partial panorama.

This PR goes with https://github.com/gopro/forgejs-samples/pull/39

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by aberthet-gpsw** [comment]
The issue about the 1/2 for has been resolved, it was a problem coming from the Share plugin https://github.com/gopro/forgejs-plugins/pull/33

**Comment by bbaudel-gpsw** [comment]
/samples/projects/camera-limits/
- [ ] seems to have issue with the limits when zoom is used. To verify

/samples/projects/paris26g/
- [x] is always unable to reach coordinates out of the 1/2 hfov & 1/2 vfov
- [ ] issue when reaching a lookat coordinate with a short path through the black tiles, cf. ALPS-1973. **WON'T FIX into this PR**
- [x] limits which are the same authorize to see a black hole at the nadir. Tiles should be visible here.
- [ ] start of the sample : the coordinate is not the default one ! Probably the same issue as camera-limits sample above. **NEW**

**Comment by bbaudel-gpsw** [comment]
/samples/projects/camera-limits/
- [ ] seems to have issue with the limits when zoom is used. To verify
Try this json camera config to reproduce the issue with a moving yaw on long fov
`"yaw":
        {
            "default": 0,
            "min": -90,
            "max": 90
        },

        "pitch":
        {
            "default": 30,
            "min": 0,
            "max": 90
        },

        "roll":
        {
            "default": 0,
            "min": 0,
            "max": 0
        },

        "fov":
        {
            "default": 50,
            "min": 20,
            "max": 100
        }`

/samples/projects/paris26g/
- [x] is always unable to reach coordinates out of the 1/2 hfov & 1/2 vfov
- [ ] issue when reaching a lookat coordinate with a short path through the black tiles, cf. ALPS-1973. **WON'T FIX into this PR**
- [x] limits which are the same authorize to see a black hole at the nadir. Tiles should be visible here.
- [x] start of the sample : the coordinate is not the default one!

**Comment by bbaudel-gpsw** [comment]
LGTM, nice edits

**Pull request merged**
