### PR TITLE
ALPS-1770 - Multiresolution tuning

### PR DESCRIPTION
**Pull request by aberthet-gpsw**
Some improvements in the multi resolution, add a preview level (also for a simple image), and some tweaks for better management of ressources and cache cleaning.

Still a WIP for now, should be good soon enough. I would like to work on two things still:
- [x] when first zooming on a portion of the scene, preview level is displayed until a tile is loaded; it isn't the case once a tile has been loaded, it remains in the cache (until a certain limit)
- [x] all level zero tiles are always added to the scene, no matter the current level; it is a big pointless weight
- [x] we need to adapt the size of the cache, given the current device (300Mo for desktop, 100Mo for mobile ?)

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by bbaudel-gpsw** [comment]
Desktop
* 150MB

Tablet/mobile
* Android 50MB
* iOS 40MB
* Windows Phone 50MB

It seems to be nice for new and old devices.

Of course recent iOS + Safari could be near 80MB and iOS + Chrome near 200MB for instance but with lower value we avoid a crash of the browser.

**Comment by aberthet-gpsw** [comment]
@bbaudel-gpsw fixed it, it was caused by the fact that we loaded a never displayed tile on boot, so now we load the middle tile of the highest level, from the front or first face, as we assume there will always be one. If you think this solution is not good, we need to revert to an all level 0 tile loading and creation.

**Comment by bbaudel-gpsw** [comment]
LGTM.

"preview" object bloc in JSON is not compatible with equirectangular preview. Need "preview": "URL" in this case.

**Pull request merged**
