### PR TITLE
Mpeg-Dash library upgrade

### PR DESCRIPTION
**Pull request by bbaudel-gpsw**
Update Mpeg-Dash engine to Dash.js 2.5.0 and apply modifications for cross-browser support

### CODE REVIEW

**Comment by rroux-gpsw** [comment]
Does this fix the dash Firefox troubles ?

**Comment by rroux-gpsw** [comment]
Firefox still don't work on my mac :(

**Comment by bbaudel-gpsw** [comment]
No it doesn't fix the FF issue yet.
It's too add the support of the last version first, then trying to fix different kinds of issues linked to the Dash.js result used as texture into Three.js.

**Comment by rroux-gpsw** [comment]
Ok, so do we have to merge this or we wait for the Firefox fix ?

**Comment by bbaudel-gpsw** [comment]
Changed PR for library upgrade only.

**Pull request merged**
