### PR TITLE
VideoCORS plugin update

### PR DESCRIPTION
**Pull request by bbaudel-gpsw**
Add support of the multiple true conditions into the FORGE.Device.check method, so the first true encounter validate the check

### CODE REVIEW

**Comment by sw-team-release-gpsw** [comment]
[CLA assistant check](https://cla.gopro.com/sign) <br/>All committers have signed the CLA.

**Comment by bbaudel-gpsw** [comment]
Solution can be to used the AND and OR operators.
Where AND properties are mandatory and OR ones should at least validate one property.

Without operator object the AND is always used.

For instance:
`
    "device":
    {
        "and":
        {
            "webgl": true
        },
        "or":
        {
            "safari": true,
            "ie": true
        }
    }
`
or
`
    "device":
    {
        "webgl": true,
        "or":
        {
            "safari": true,
            "ie": true
        }
    }
`

In this case the parse must be recursive to be able to check AND and OR into AND and OR main objects.
I'll add a specific sample for that.

Need to add Unit test on the check method.

**Comment by bbaudel-gpsw** [comment]
Other samples:

- Test 1

> "NOT desktop AND webGL"

```
"devices":
{
    "desktop": false,
    "webGL": true
}
```

OR

```
"devices":
{
    "and":
    {
        "desktop": false,
        "webGL": true
    }
}
```

- Test 2

> "NOT isAndroidStockBrowser OR webGL"

```
"devices":
{
    "or":
    {
        "isAndroidStockBrowser": false,
        "webGL": true
    }
}
```

- Test 3

> "tablet OR mobile AND NOT iPhone"
> "tablet OR (mobile AND NOT iPhone)"

```
"devices":
{
    "or":
    {
        "tablet": true,
        "and":
        {
            "mobile": true,
            "iPhone": false
        }
    }
}
```

- Test 4

> "mp4Video AND NOT webGL OR mp4Video AND webGL AND desktop OR mp4Video AND webGL AND NOT ie"
> "(mp4Video AND NOT webGL) OR (mp4Video AND webGL AND desktop) OR (mp4Video AND webGL AND NOT ie)"
> "mp4Video AND (NOT webGL OR (webGL AND desktop) OR (webGL AND NOT ie))"

```
"devices":
{
    "or":
    {
        "and":
        {
            "mp4Video": true,
            "webGL": false
        },
        "and"
        {
            "mp4Video": true,
            "webGL": true,
            "desktop": true
        },
        "and"
        {
            "mp4Video": true,
            "webGL": true,
            "ie": false
        }
    }
}
```

OR

```
"devices":
{
    "and":
    {
        "mp4Video": true,
        "or":
        {
            "webGL": false,
            "and"
            {
                "webGL": true,
                "desktop": true
            },
            "and"
            {
                "webGL": true,
                "ie": false
            }
        }
    }
}
```

- Test 5

> "desktop AND safari AND safariVersion < 9 OR iOS AND safari AND safariVersion < 10"

_Not possible with just AND/OR !_

**Comment by rroux-gpsw** [comment]
Thanks for the specs @bbaudel-gpsw. We have to add this into the backlog now :)

**Comment by bbaudel-gpsw** [comment]
Cf. #101 for the resolution

**Pull request closed without merging**
